# Errors
INVALID_CHOICE =                "\n~~~~~~~~~~~~~~~ ERROR: Invalid choice :/, try again ~~~~~~~~~~~~~\n"
DIVISION_BY_ZERO =              "\n~~~~~~~~~~ ERROR: Divisions by 0 are INFINITEEEEEE :/ ~~~~~~~~~~~\n"
INVALID_VALUE_RIGHT_CLOSING_PAR="~~~~~~~~~ ERROR: Invalid value to the right of ')' :/ ~~~~~~~~~~~\n"
INVALID_VALUE_LEFT_CLOSING_PAR ="~~~~~~~~~~~ ERROR: Invalid value to the left of ')' :/ ~~~~~~~~~~\n"
INVALID_VALUE_RIGHT_OPEN_PAR =  "~~~~~~~~~ ERROR: Invalid value to the right of '(' :/ ~~~~~~~~~~~\n"
INVALID_VALUE_LEFT_OPEN_PAR =   "~~~~~~~~~~~ ERROR: Invalid value to the left of '(' :/ ~~~~~~~~~~\n"
WRONG_ORDER_PARENTHESIS =       "~~~~ ERROR: Closing parenthesis before open parenthesis found ~~~\n"
EXTRA_OR_MISSING_PAR =          "~~~~~~~~ ERROR: Extra or missing parenthesis detected :/ ~~~~~~~~\n"
EMPTY_PARENTHESIS =             "~~~~~~~~~~~~ ERROR: Empty parenthesis detected :/ ~~~~~~~~~~~~~~~\n"
FIRST_LAST_VALUES_PAR =         "~ ERROR: 1st and last values have to be numbers or parenthesis ~~\n"
OPERATORS_TOGETHER =            "~~~~~~~~~~~ ERROR: Two operators can not go together :/ ~~~~~~~~~\n"
INVALID_SYMBOL_OR_VALUE =       "~~~~~~~ ERROR: Invalid symbol or value in expression :/ ~~~~~~~~~\n"
NO_EXPRESSION =                 "\n~~ ERROR: No expression entered. Next time enter an expression ~~\n"